### ISSUE TITLE
First startup fails due to missing function

### ISSUE THREAD

**Issue by garetheowen** [orangecoding/heatsheet#1]
When running for first time on a mac.  Get an unhandled exception for no function _recording() at line 48 of lib/recording/DataRecording.js.
Changed _recording() call to _fetchData() and now ***seems* to work?

**Comment by ghost** [comment]
It's working for me  with the change _recording --> _fetchData()
now importing

**Comment by orangecoding** [comment]
Fixed here:
https://github.com/orangecoding/heatsheet/pull/3

Thanks! ❤️
