### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: this._recording is not a function

### ISSUE THREAD

**Issue by avdl72** [orangecoding/heatsheet#2]
I receive this error every 10 minutes:

yarn run v1.22.5
$ node index.js
2020-10-08 16:36:44 Warming up database successful
2020-10-08 16:36:45 Started recording scheduler
2020-10-08 16:36:45 Started API service on port 9999
2020-10-08 16:36:46 Initial Migration is needed. Starting now. This might take a while, grab a cup of coffee...
(node:6569) UnhandledPromiseRejectionWarning: TypeError: this._recording is not a function
    at /home/pi/heatsheet/lib/recording/DataRecording.js:48:20
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:6569) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6569) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by garetheowen** [comment]
This is the same issue that I raised a while back - see issue #1 - there is a fix included in the body of the issue.

**Comment by orangecoding** [comment]
Fixed here:
https://github.com/orangecoding/heatsheet/pull/3

Thanks! ❤️
